export const projects = [
    {
      id: 1,
      title: 'Redingale',
      description: 'An AI-supported product design app.',
      image: '/redingale.png',
      details: {
        screenshots: ['/redingale/1.png', '/redingale/2.png','/redingale/3.png', '/redingale/4.png','/redingale/5.png', 
          '/redingale/6.png','/redingale/7.png','/redingale/8.png','/redingale/9.png','/redingale/10.png',
          '/redingale/11.png','/redingale/12.png','/redingale/13.png','/redingale/14.png','/redingale/15.png'],
        description: 'This project is a modern web app that uses React for the frontend. The backend part was coded by my other 2 teammates. On this site, users can create their own custom designs with images they upload or images generated by artificial intelligence.',
        technologies: ['React.js', 'Redux', 'Material UI', 'PostgreSQL'],
      },
    },
    {
      id: 2,
      title: 'Lumino Hosting',
      description: 'Minecraft server hosting app.',
      image: '/luminohosting.jpeg',
      details: {
        screenshots: ['/minecraft/1.png', '/minecraft/2.png','/minecraft/3.png','/minecraft/4.png','/minecraft/5.png',
          '/minecraft/6.png','/minecraft/7.png','/minecraft/8.png','/minecraft/9.png','/minecraft/10.png',
          '/minecraft/11.png','/minecraft/12.png','/minecraft/13.png','/minecraft/14.png','/minecraft/15.png',
          '/minecraft/16.png','/minecraft/17.png'
        ],
        description: 'This project is a minecraft server hosting site. In this project I coded the user interface with React.js.',
        technologies: ['React.js', 'Scss', 'Redux'],
      },
    },
    {
      id: 3,
      title: 'Performance Evaulation',
      description: 'Employee performance evaluation application.',
      image: '/performance.png',
      details: {
        screenshots: ['/performance/1.png', '/performance/2.png', '/performance/3.png', , '/performance/4.png',
          , '/performance/5.png', '/performance/6.png',, '/performance/7.png', '/performance/8.png', '/performance/9.png'
          , '/performance/10.png', '/performance/11.png', '/performance/12.png', '/performance/13.png'
        ],
        description: 'An application that evaluates the performance of company employees. I coded this application during my 20-day mandatory summer internship. I was given the task of coding the interface of the application.',
        technologies: ['React.js', 'Redux', 'Material UI'],
      },
    },
    {
      id: 4,
      title: 'My Portfolio',
      description: 'A responsive portfolio website with modern UI/UX.',
      image: '/owl.png',
      details: {
        screenshots: ['/owl.png'],
        description: 'This project is a fully responsive portfolio website with a modern design and user-friendly interface.',
        technologies: ['React', 'SCSS'],
      },
    },
    {
      id: 5,
      title: 'Real Estate',
      description: 'A responsive e-commerce website with modern UI/UX.',
      image: '/realestate.png',
      details: {
        screenshots: ['/owl.png', '/owl.png'],
        description: 'This project is a fully responsive e-commerce website with a modern design and user-friendly interface.',
        technologies: ['React', 'Redux', 'SCSS', 'MongoDB'],
      },
    },
    {
      id: 6,
      title: 'Propeller Health Classification',
      description: 'An application that detects propeller health.',
      image: '/propeller.png',
      details: {
        screenshots: ['/propeller/1.png', '/propeller/2.png','/propeller/3.png','/propeller/4.png','/propeller/6.png',
          '/propeller/6.png','/propeller/7.png','/propeller/8.png','/propeller/9.png','/propeller/10.png',
          '/propeller/11.png'
        ],
        description: 'This project is a machine learning project developed using a csv dataset consisting of propeller sounds. In this project, I first determined whether the propellers were healthy by using the dataset. Then, I determined the problem of the propellers that were not healthy.',
        technologies: ['Python'],
      },
    },
    {
      id: 7,
      title: 'Voice Command Classification',
      description: 'An application that detects user voice commands',
      image: '/voicecommand.png',
      details: {
        screenshots: ['/voice/1.png', '/voice/2.png','/voice/3.png', '/voice/4.png', '/voice/5.png', 
          '/voice/6.png', '/voice/7.png', '/voice/8.png', '/voice/9.png', '/voice/10.png', '/voice/11.png', 
          '/voice/12.png', '/voice/13.png', '/voice/14.png', '/voice/15.png'
        ],
        description: 'This project is a machine learning project developed using a dataset of command audio files. The dataset was used to determine which command the audio files were.',
        technologies: ['Python'],
      },
    },
    {
      id: 8,
      title: 'Book Recommendation App',
      description: 'An application that recommends books based on user tastes.',
      image: '/book.png',
      details: {
        screenshots: ['/book/1.png',  '/book/2.png','/book/3.png','/book/4.png','/book/5.png','/book/6.png',
          '/book/7.png'
        ],
        description: 'The book recommendation application we made in the big data course. In this application, we performed big data analysis using hdfs and pyspark. Then, we made recommendations based on the books that users had previously rated.',
        technologies: ['Python', 'HDFS', 'Spark'],
      },
    },
    
  ];